ninja_tooken_user_old:
    path:  /utilisateur.php
    controller: App\Controller\UserController::oldUser

ninja_tooken_user_find:
    path:  /compte/messagerie/user/find
    controller: App\Controller\UserController::userFind
    methods: [GET]

ninja_tooken_user_registration_register:
    path:  /register
    controller: App\Controller\UserController::register
    methods: [GET]

ninja_tooken_user_security_login:
    path:  /login
    controller: App\Controller\UserController::login
    methods: [GET, POST]

ninja_tooken_user_security_check:
    path:  /login
    controller: App\Controller\UserController::check
    methods: [POST]

ninja_tooken_user_resetting_request:
    path: /request
    controller: App\Controller\ResettingController::request
    methods: [GET]

ninja_tooken_user_resetting_send_email:
    path: /send-email
    controller: App\Controller\ResettingController::sendEmail
    methods: [POST]

ninja_tooken_user_resetting_check_email:
    path: /check-email
    controller: App\Controller\ResettingController::checkEmail
    methods: [GET]

ninja_tooken_user_resetting_reset:
    path: /reset/{token}
    controller: App\Controller\ResettingController::reset
    methods: [GET, POST]

ninja_tooken_user_autologin:
    path:  /auto/{autologin}
    controller: App\Controller\UserController::autologin
    methods: [GET, POST]

ninja_tooken_user_desinscription:
    path:  /desinscription/{email}
    controller: App\Controller\UserController::desinscription
    methods: [GET, POST]

ninja_tooken_user_fiche:
    path:  /fiche/{user_nom}/{page}
    controller: App\Controller\UserController::fiche
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_messagerie_envoi:
    path:  /compte/messagerie/envoi/{page}
    controller: App\Controller\UserController::messagerieEnvoi
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_messagerie:
    path:  /compte/messagerie/{page}
    controller: App\Controller\UserController::messagerie
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_parametres:
    path:  /compte/parametres
    controller: App\Controller\UserController::parametres

ninja_tooken_user_profile_show:
    path:  /compte/parametres
    controller: App\Controller\UserController::parametres

ninja_tooken_user_parametres_update:
    path:  /compte/parametres/update
    controller: App\Controller\UserController::parametresUpdate

ninja_tooken_user_parametres_update_avatar:
    path:  /compte/parametres/update-avatar
    controller: App\Controller\UserController::parametresUpdateAvatar

ninja_tooken_user_parametres_confirm_mail:
    path:  /compte/parametres/confirm-mail
    controller: App\Controller\UserController::parametresConfirmMail

ninja_tooken_user_parametres_update_password:
    path:  /compte/parametres/update-password
    controller: App\Controller\UserController::parametresUpdatePassword

ninja_tooken_user_parametres_delete_account:
    path:  /compte/parametres/delete-account
    controller: App\Controller\UserController::parametresDeleteAccount

ninja_tooken_user_amis:
    path:  /compte/amis/{page}
    controller: App\Controller\UserController::amis
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_amis_demande:
    path:  /compte/amis/demande/{page}
    controller: App\Controller\UserController::amisDemande
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_amis_blocked:
    path:  /compte/amis/bloquer/{page}
    controller: App\Controller\UserController::amisBlocked
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_amis_confirmer:
    path:  /compte/amis/confirm/{id}
    controller: App\Controller\UserController::amisConfirmer
    requirements:
        id:  \d*

ninja_tooken_user_amis_bloquer_supprimer_tout:
    path:  /compte/amis/block/supprimer-all
    controller: App\Controller\UserController::amisBlockedSupprimer

ninja_tooken_user_amis_bloquer:
    path:  /compte/amis/block/{id}
    controller: App\Controller\UserController::amisBloquer
    requirements:
        id:  \d*

ninja_tooken_user_amis_debloquer:
    path:  /compte/amis/debloquer/{id}
    controller: App\Controller\UserController::amisDebloquer
    requirements:
        id:  \d*

ninja_tooken_user_amis_supprimer:
    path:  /compte/amis/supprimer/{id}
    controller: App\Controller\UserController::amisSupprimer
    requirements:
        id:  \d*

ninja_tooken_user_amis_demande_supprimer_tout:
    path:  /compte/amis/demande/supprimer-all
    controller: App\Controller\UserController::amisDemandeSupprimer


ninja_tooken_user_captures:
    path:  /compte/captures/{page}
    controller: App\Controller\UserController::captures
    defaults:
        page: 1
    requirements:
        page:  \d*

ninja_tooken_user_captures_supprimer:
    path:  /compte/captures/{id}/supprimer/
    controller: App\Controller\UserController::capturesSupprimer
    requirements:
        id:  \d*